version: "3"

services:
  web:
    build: .
    ports:
      - "4568:4567"
    depends_on:
      - db
    environment:
      - "TZ=Asia/Tokyo"

  db:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: "test"
      MYSQL_USER: "test"
      TZ: "Asia/Tokyo"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "3308:3306"
